### ISSUE TITLE
Issue with Dumpsc within the latest Brawl Stars Version (38.111)

### ISSUE THREAD

**Issue by DEV-DIBSTER** [Galaxy1036/Dumpsc#2]
As of the latest version of Brawl Stars (38.111), the file compression has changed on the .sc files, which returns a error while attempting to retrieve latest game assets, including Star Power Icons, Gadget Icons, Brawler Icons. and Player Icons.

I'm not 100% sure exactly what has changed, but I have a rough idea on it. I'm using the forked repository by statscell (https://github.com/Statscell/Dumpsc), which combines this repository and XCoder to create a .sc file converter and Image splitter.

Best regards ✌️

**Comment by Galaxy1036** [comment]
Should be fixed now :)
